### ISSUE TITLE
[Feature request] Retain old comment in result file

### ISSUE THREAD

**Issue by inariksit** [harisont/concept-alignment#35]
I'm running `extract-concepts` on a conllu file that has sentences like the following, starting with a comment:

```
# <http://snomed.info/id/188462001>
1	Secondary	secondary	ADJ	<*>.A.ABS.<SS>	Degree=Pos	3	amod	_	_
2	malignant	malignant	ADJ	A.ABS	Degree=Pos	3	amod	_	_
3	neoplasm	neoplasm	NOUN	N.NOM.SG	Case=Nom|Number=Sing	0	root	_	_
4	of	of	ADP	PREP	AdpType=Prep	5	case	_	_
5	brain	brain	NOUN	<Count>.N.NOM.SG	Case=Nom|Number=Sing	3	nmod	_	_
6	and	and	CCONJ	CC.@CC	_	7	cc	_	_
7	spinal cord	spinal cord	NOUN	<Count>.N.NOM.SG	Case=Nom|Number=Sing	5	conj	_	_
```

In the result, the original comment has been replaced with new ones:

```
# sent_id = gfud1000002
# text = of brain and spinal cord
# reasons: {POS, UD} sentence IDs: {"missing sent_id"} correctness: _
1	of	of	ADP	PREP	AdpType=Prep	2	case	_	ADJUSTED=True
2	brain	brain	NOUN	<Count>.N.NOM.SG	Case=Nom|Number=Sing	0	root	_	ADJUSTED=True|ORIG_LABEL=nmod
3	and	and	CCONJ	CC.@CC	_	4	cc	_	ADJUSTED=True
4	spinal cord	spinal cord	NOUN	<Count>.N.NOM.SG	Case=Nom|Number=Sing	2	conj	_	ADJUSTED=True
```

I would like to know where the fragment came from, so I'd like the original comment to be retained in the output, something like the following. Placement doesn't matter, just that it is there somewhere.

```
# sent_id = gfud1000002
# text = of brain and spinal cord
# <http://snomed.info/id/188462001>
…
```

**Comment by inariksit** [comment]
Oh, I noticed that if I put the comment in as `# sent_id = <original comment>`, then it actually includes much more helpful output. So nevermind, it works already! 😁

**Comment by harisont** [comment]
> Oh, I noticed that if I put the comment in as `# sent_id = <original comment>`, then it actually includes much more helpful output. So nevermind, it works already! grin

Yeah right, even though it would also make sense to retain original comments that have nothing to do with the sentence id.
I had thought about this but I seem to recall that gf-ud (the UDConcept module, which I'm using pretty much everywhere) was making that slightly annoying to implement.
